"""
decision/train.py
=================
NeuroDrive-XAI decision model training pipeline.

Data priority:
  1. Real BDD100K features (dataset/real_features.csv) — generated by
     dataset/generate_features.py — preferred
  2. Legacy synthetic features (dataset/hybrid_features.csv) — fallback
  3. Auto-generate synthetic data if neither exists (dev mode)

Training:
  - NeuroDecisionMLP (PyTorch) — dual-head: steering (MSE) + brake (BCE)
  - 80/20 stratified split on brake label
  - StandardScaler fitted on train only
  - Saves: weights/neurodrive_mlp.pth, weights/feature_scaler.pkl

Usage:
    python decision/train.py                                 # auto-select data
    python decision/train.py --data dataset/real_features.csv
    python decision/train.py --data dataset/real_features.csv --epochs 50
"""

import argparse
import os
import sys

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, Dataset

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from decision.mlp_model import NeuroDecisionMLP
import joblib


# ──────────────────────────────────────────────────── Dataset class ──────────
class NeuroDriveDataset(Dataset):
    def __init__(self, X, y_steer, y_brake):
        self.X = torch.FloatTensor(X)
        self.y_steer = torch.FloatTensor(y_steer).unsqueeze(1)
        self.y_brake = torch.FloatTensor(y_brake).unsqueeze(1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y_steer[idx], self.y_brake[idx]


# ──────────────────────────────────────────────────── Synthetic fallback ──────
def _generate_synthetic_data(n: int = 2000) -> pd.DataFrame:
    """
    Generate realistic synthetic driving scenarios when no dataset exists.
    Covers: highway, urban, emergency scenarios.
    """
    print("  Generating synthetic training data (dev mode)...")
    np.random.seed(42)
    rows = []
    type_map = ["car", "pedestrian", "bike", "truck", "none"]

    # Highway: far objects, straight road
    for _ in range(n // 4):
        dist = np.random.uniform(30, 120)
        rows.append({
            "distance_to_object":  dist,
            "relative_velocity":   np.random.uniform(-5, 5),
            "lane_offset":         np.random.uniform(-0.5, 0.5),
            "lane_curvature":      np.random.uniform(0.0, 0.02),
            "num_objects":         np.random.randint(1, 4),
            "closest_object_type": 0,  # car
            "steering_angle":      np.random.uniform(-0.05, 0.05),
            "brake":               0,
        })

    # Urban: variable distance, moderate curvature
    for _ in range(n // 4):
        dist = np.random.uniform(10, 50)
        brake = 1 if dist < 15 else 0
        rows.append({
            "distance_to_object":  dist,
            "relative_velocity":   np.random.uniform(-15, 5),
            "lane_offset":         np.random.uniform(-1.5, 1.5),
            "lane_curvature":      np.random.uniform(0.0, 0.08),
            "num_objects":         np.random.randint(2, 8),
            "closest_object_type": np.random.choice([0, 1, 2, 3]),
            "steering_angle":      np.random.uniform(-0.3, 0.3),
            "brake":               brake,
        })

    # Emergency: very close objects, hard brake
    for _ in range(n // 4):
        dist = np.random.uniform(1, 12)
        rows.append({
            "distance_to_object":  dist,
            "relative_velocity":   np.random.uniform(-30, -5),
            "lane_offset":         np.random.uniform(-2.0, 2.0),
            "lane_curvature":      np.random.uniform(0.0, 0.1),
            "num_objects":         np.random.randint(1, 6),
            "closest_object_type": np.random.choice([0, 1, 2, 3]),
            "steering_angle":      np.random.uniform(-0.1, 0.1),
            "brake":               1,
        })

    # Pedestrian edge cases: sudden crossings
    for _ in range(n // 4):
        dist = np.random.uniform(5, 25)
        rows.append({
            "distance_to_object":  dist,
            "relative_velocity":   np.random.uniform(-20, 0),
            "lane_offset":         np.random.uniform(-1.0, 1.0),
            "lane_curvature":      np.random.uniform(0.0, 0.05),
            "num_objects":         np.random.randint(1, 4),
            "closest_object_type": 1,  # pedestrian
            "steering_angle":      np.random.uniform(-0.2, 0.2),
            "brake":               1 if dist < 18 else 0,
        })

    return pd.DataFrame(rows)


# ──────────────────────────────────────────────────── Main pipeline ────────
def train_pipeline(
    data_path: str = None,
    epochs: int = 40,
    batch_size: int = 32,
    lr: float = 0.001,
):
    print("\n" + "=" * 60)
    print("NeuroDrive-XAI — Decision Model Training")
    print("=" * 60)

    # ── 1. Select data source ─────────────────────────────────────────
    if data_path and os.path.exists(data_path):
        print(f"  Data source: {data_path} (specified)")
    elif os.path.exists("dataset/real_features.csv"):
        data_path = "dataset/real_features.csv"
        print(f"  Data source: {data_path} (real BDD100K features)")
    elif os.path.exists("dataset/hybrid_features.csv"):
        data_path = "dataset/hybrid_features.csv"
        print(f"  Data source: {data_path} (legacy synthetic)")
    else:
        data_path = None
        print("  Data source: auto-generated synthetic (no CSV found)")

    # ── 2. Load / generate data ───────────────────────────────────────
    if data_path:
        df = pd.read_csv(data_path)
        print(f"  Loaded {len(df):,} rows from {data_path}")
    else:
        df = _generate_synthetic_data(2000)
        print(f"  Generated {len(df):,} synthetic rows")

    # ── 3. Feature encoding ───────────────────────────────────────────
    type_map = {"car": 0, "pedestrian": 1, "bike": 2, "truck": 3, "none": 4}
    if df["closest_object_type"].dtype == object:
        df["closest_object_type"] = df["closest_object_type"].map(type_map).fillna(4)

    FEATURES = [
        "distance_to_object", "relative_velocity", "lane_offset",
        "lane_curvature", "num_objects", "closest_object_type",
    ]
    for col in FEATURES:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0.0)

    X = df[FEATURES].values
    y_steer = df["steering_angle"].values.astype(np.float32)
    y_brake = df["brake"].values.astype(np.float32)

    # Brake rate info
    brake_rate = y_brake.mean()
    print(f"\n  Brake=1 rate  : {brake_rate*100:.1f}%")
    print(f"  Dataset size  : {len(df):,}")
    print(f"  Features      : {FEATURES}")

    # ── 4. Stratified 80/20 split ─────────────────────────────────────
    X_train, X_test, ys_train, ys_test, yb_train, yb_test = train_test_split(
        X, y_steer, y_brake,
        test_size=0.2,
        random_state=42,
        stratify=(y_brake > 0.5).astype(int),  # stratify on binary brake
    )
    print(f"\n  Train set: {len(X_train):,} | Test set: {len(X_test):,}")

    # ── 5. Fit StandardScaler on train only ───────────────────────────
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s  = scaler.transform(X_test)

    os.makedirs("weights", exist_ok=True)
    joblib.dump(scaler, "weights/feature_scaler.pkl")
    print("  ✓ StandardScaler saved → weights/feature_scaler.pkl")

    # ── 6. DataLoaders ────────────────────────────────────────────────
    train_ds = NeuroDriveDataset(X_train_s, ys_train, yb_train)
    test_ds  = NeuroDriveDataset(X_test_s,  ys_test,  yb_test)
    train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True,  drop_last=True)
    test_dl  = DataLoader(test_ds,  batch_size=batch_size, shuffle=False)

    # ── 7. Model & optimiser ─────────────────────────────────────────
    model = NeuroDecisionMLP(input_features=6)
    steer_loss_fn = nn.MSELoss()
    brake_loss_fn = nn.BCELoss()

    # Class-weighted BCE for imbalanced brake labels
    pos_weight = torch.tensor([(1 - brake_rate) / max(brake_rate, 1e-3)])
    brake_loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    optimizer  = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler  = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    print(f"\n  Training: {epochs} epochs | lr={lr} | batch={batch_size}")
    print("-" * 60)

    # ── 8. Training loop ──────────────────────────────────────────────
    best_val = float("inf")
    for epoch in range(epochs):
        model.train()
        train_loss = 0.0

        for bx, bys, byb in train_dl:
            optimizer.zero_grad()
            p_steer, p_brake = model(bx)
            loss = steer_loss_fn(p_steer, bys) + brake_loss_fn(p_brake, byb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            train_loss += loss.item()

        scheduler.step()

        # Validation
        model.eval()
        val_loss = 0.0
        brake_correct = 0
        total = 0
        with torch.no_grad():
            for bx, bys, byb in test_dl:
                p_steer, p_brake = model(bx)
                val_loss += (steer_loss_fn(p_steer, bys) + brake_loss_fn(p_brake, byb)).item()
                pred_brake = (torch.sigmoid(p_brake) > 0.5).float()
                brake_correct += (pred_brake == byb).sum().item()
                total += byb.size(0)

        t_l  = train_loss / len(train_dl)
        v_l  = val_loss / len(test_dl)
        acc  = brake_correct / max(total, 1) * 100

        if v_l < best_val:
            best_val = v_l
            torch.save(model.state_dict(), "weights/neurodrive_mlp_best.pth")

        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(
                f"  Epoch [{epoch+1:3d}/{epochs}] "
                f"| Train: {t_l:.4f} | Val: {v_l:.4f} "
                f"| Brake Acc: {acc:.1f}%"
            )

    # ── 9. Save final model ───────────────────────────────────────────
    torch.save(model.state_dict(), "weights/neurodrive_mlp.pth")
    print("\n" + "=" * 60)
    print(f"  ✓ Model saved → weights/neurodrive_mlp.pth")
    print(f"  ✓ Best val saved → weights/neurodrive_mlp_best.pth")
    print(f"  Best val loss: {best_val:.4f}")
    print("=" * 60)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data",    type=str, default=None,  help="Path to feature CSV")
    parser.add_argument("--epochs",  type=int, default=40,    help="Training epochs")
    parser.add_argument("--batch",   type=int, default=32,    help="Batch size")
    parser.add_argument("--lr",      type=float, default=0.001)
    args = parser.parse_args()
    train_pipeline(args.data, args.epochs, args.batch, args.lr)
